apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: "heidiks/rabbitmq-delayed-message-exchange:latest"
          ports:
            - containerPort: 5672
            - containerPort: 15672
          env:
            - name: RABBITMQ_DEFAULT_PASS
              value: "secret"
            - name: RABBITMQ_DEFAULT_USER
              value: "myuser"

        # RabbitMQ Exporter sidecar container
        - name: rabbitmq-exporter
          image: kbudde/rabbitmq-exporter:latest
          ports:
            - containerPort: 15692
          env:
            - name: RABBIT_URL
              value: "http://localhost:15672"
          # Optional environment variables for additional configuration
          # Refer to rabbitmq-exporter documentation for more options

---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
spec:
  selector:
    app: rabbitmq
  ports:
    - protocol: TCP
      name: amqp
      port: 5672
      targetPort: 5672
    - protocol: TCP
      name: management
      port: 15672
      targetPort: 15672
    - protocol: TCP
      name: exporter
      port: 15692
      targetPort: 15692 # Expose the exporter port for Prometheus scraping
  type: LoadBalancer
